gerbil_version: "1.5.0"
pangolin_version: "ee-1.21.1"
traefik_version: "v3.7.11"
badger_version: "v1.6.1"
crowdsec_traefik_version: "v1.7.1"
crowdsec_version: "latest"
crowdsec_manager_version: "latest"
newt_enabled: false
newt_version: "latest"
newt_pangolin_endpoint: ""
newt_id: ""
newt_secret: ""
pangolin_compose_path: "/data/pangolin"
pangolin_traefik_path: "/data/pangolin/config/traefik"
